package didameetings.server;

/* these imported classes are generated by the contract */
import didameetings.DidaMeetingsMain;
import didameetings.DidaMeetingsMainServiceGrpc;

import io.grpc.stub.StreamObserver;

public class DidaMeetingsMainServiceImpl extends DidaMeetingsMainServiceGrpc.DidaMeetingsMainServiceImplBase {

    DidaMeetingsServerState server_state;
    
    public DidaMeetingsMainServiceImpl(DidaMeetingsServerState state) {
        this.server_state = state;
    }

    @Override
    public void open(DidaMeetingsMain.OpenRequest request, StreamObserver<DidaMeetingsMain.OpenReply> responseObserver) {
	// for debug purposes
	System.out.println("Receiving open request:" + request);

	// Apply slow mode delay (not for console requests)
	this.server_state.applySlowModeDelay();

	int reqid = request.getReqid();
	int mid   = request.getMeetingid();

	// for debug purposes
	System.out.println("reqid " + reqid + " meetingid " + mid);

	DidaMeetingsCommand command = new DidaMeetingsCommand (DidaMeetingsAction.OPEN, mid);

	RequestRecord request_record;
	// Synchronized block to ensure instance assignment follows reception order
	synchronized (this.server_state) {
		// Assign instance number and add to pending atomically
		int instanceNumber = this.server_state.assignNextInstance();
		
		// for debug purposes
		System.out.println("Adding open request with reqid " + reqid + " to pending with instance " + instanceNumber);

		request_record = new RequestRecord (reqid, command, instanceNumber);
		this.server_state.req_history.addToPending (reqid, request_record);
	}
	this.server_state.main_loop.wakeup ();
	boolean result = request_record.waitForResponse();

	// for debug purposes
	System.out.println("Result is ready for open request with reqid " + reqid);
	
	// Get the logical timestamp when this command was executed
	int logicalTimestamp = request_record.getLogicalTimestamp();
	
	DidaMeetingsMain.OpenReply response = DidaMeetingsMain.OpenReply.newBuilder()
		.setReqid(reqid)
		.setResult(result)
		.setLogicalTimestamp(logicalTimestamp)
		.build();
	responseObserver.onNext(response);
	responseObserver.onCompleted();
    }

    @Override
    public void add(DidaMeetingsMain.AddRequest request, StreamObserver<DidaMeetingsMain.AddReply> responseObserver) {
	// for debug purposes
	System.out.println("Receiving add request:" + request);

	// Apply slow mode delay (not for console requests)
	this.server_state.applySlowModeDelay();

	int reqid = request.getReqid();
	int mid   = request.getMeetingid();
	int pid   = request.getParticipantid();

	// for debug purposes
	System.out.println("reqid " + reqid + " meetingid " + mid  + " participantid " + pid);

	DidaMeetingsCommand command = new DidaMeetingsCommand (DidaMeetingsAction.ADD, mid, pid);

	// Notify Fast Paxos manager about ADD request - enables predictive execution
	this.server_state.notifyAddRequest(mid, pid);

	RequestRecord request_record;
	// Synchronized block to ensure instance assignment follows reception order
	synchronized (this.server_state) {
		// Assign instance number and add to pending atomically
		int instanceNumber = this.server_state.assignNextInstance();
		
		// for debug purposes
		System.out.println("Adding add request with reqid " + reqid + " to pending with instance " + instanceNumber);

		request_record = new RequestRecord (reqid, command, instanceNumber);
		this.server_state.req_history.addToPending (reqid, request_record);
	}
	this.server_state.main_loop.wakeup ();
	boolean result = request_record.waitForResponse();

	// for debug purposes
	System.out.println("Result is ready for add request with reqid " + reqid);
	
	// Get the logical timestamp when this command was executed
	int logicalTimestamp = request_record.getLogicalTimestamp();
	
	DidaMeetingsMain.AddReply response = DidaMeetingsMain.AddReply.newBuilder()
		.setReqid(reqid)
		.setResult(result)
		.setLogicalTimestamp(logicalTimestamp)
		.build();
	
	responseObserver.onNext(response);
	responseObserver.onCompleted();
    }

    
    @Override
    public void topic(DidaMeetingsMain.TopicRequest request, StreamObserver<DidaMeetingsMain.TopicReply> responseObserver) {
	// for debug purposes
	System.out.println("Receiving topic request:" + request);

	// FAST PAXOS: All servers participate in Fast Paxos
	System.out.println("[FAST_TOPIC] Server " + this.server_state.my_id + " processing TOPIC request " + request.getReqid());

	// Apply slow mode delay (not for console requests)
	this.server_state.applySlowModeDelay();

	int reqid = request.getReqid();
	int mid   = request.getMeetingid();
	int pid   = request.getParticipantid();
	int topic = request.getTopicid();

	// for debug purposes
	System.out.println("[FAST_TOPIC] reqid " + reqid + " meetingid " + mid);

	DidaMeetingsCommand command = new DidaMeetingsCommand (DidaMeetingsAction.TOPIC, mid, pid, topic);

	// FAST PAXOS: TOPIC operations use Fast Paxos with logical timestamp synchronization
	System.out.println("[FAST_TOPIC] TOPIC request " + reqid + " using Fast Paxos with timestamp synchronization");
	
	// Get client's logical timestamp for synchronization
	int clientTimestamp = request.getClientTimestamp(); // Client's last known Multi-Paxos timestamp
	System.out.println("[FAST_TOPIC] Client timestamp: " + clientTimestamp + ", server timestamp: " + this.server_state.getCurrentLogicalTimestamp());
	
	// Create request record for Fast Paxos (NO instance assignment, NO pending queue)
	RequestRecord request_record = new RequestRecord(reqid, command);
	
	// Process via Fast Paxos with timestamp synchronization (queue handled internally)
	boolean result = this.server_state.processfastTopicRequest(request_record, clientTimestamp);
	
	DidaMeetingsMain.TopicReply response = DidaMeetingsMain.TopicReply.newBuilder().setReqid(reqid).setResult(result).build();
	
	responseObserver.onNext(response);
	responseObserver.onCompleted();
    }


    @Override
    public void close(DidaMeetingsMain.CloseRequest request, StreamObserver<DidaMeetingsMain.CloseReply> responseObserver) {
	// for debug purposes
	System.out.println("Receiving close request:" + request);

	// Apply slow mode delay (not for console requests)
	this.server_state.applySlowModeDelay();

	int reqid = request.getReqid();
	int mid   = request.getMeetingid();

	// for debug purposes
	System.out.println("reqid " + reqid + " meetingid " + mid);

	DidaMeetingsCommand command = new DidaMeetingsCommand (DidaMeetingsAction.CLOSE, mid);

	RequestRecord request_record;
	// Synchronized block to ensure instance assignment follows reception order
	synchronized (this.server_state) {
		// Assign instance number and add to pending atomically
		int instanceNumber = this.server_state.assignNextInstance();
		
		// for debug purposes
		System.out.println("Adding close request with reqid " + reqid + " to pending with instance " + instanceNumber);

		request_record = new RequestRecord (reqid, command, instanceNumber);
		this.server_state.req_history.addToPending (reqid, request_record);
	}
	this.server_state.main_loop.wakeup ();
	boolean result = request_record.waitForResponse();

	// for debug purposes
	System.out.println("Result is ready for close request with reqid " + reqid);
	
	DidaMeetingsMain.CloseReply response = DidaMeetingsMain.CloseReply.newBuilder()
		.setReqid(reqid)
		.setResult(result)
		.build();
	
	responseObserver.onNext(response);
	responseObserver.onCompleted();
    }


    @Override
    public void dump(DidaMeetingsMain.DumpRequest request, StreamObserver<DidaMeetingsMain.DumpReply> responseObserver) {
	// for debug purposes
	System.out.println("Receiving dump request:" + request);

	// Apply slow mode delay (not for console requests)
	this.server_state.applySlowModeDelay();

	int reqid = request.getReqid();

	// for debug purposes
	System.out.println("reqid " + reqid);

	DidaMeetingsCommand command = new DidaMeetingsCommand (DidaMeetingsAction.DUMP);

	RequestRecord request_record;
	// Synchronized block to ensure instance assignment follows reception order
	synchronized (this.server_state) {
		// Assign instance number and add to pending atomically
		int instanceNumber = this.server_state.assignNextInstance();
		
		// for debug purposes
		System.out.println("Adding dump request with reqid " + reqid + " to pending with instance " + instanceNumber);

		request_record = new RequestRecord (reqid, command, instanceNumber);
		this.server_state.req_history.addToPending (reqid, request_record);
	}
	this.server_state.main_loop.wakeup ();
	boolean result = request_record.waitForResponse();

	// for debug purposes
	System.out.println("Result is ready for dump request with reqid " + reqid);
	
	DidaMeetingsMain.DumpReply response = DidaMeetingsMain.DumpReply.newBuilder()
		.setReqid(reqid)
		.setResult(result)
		.build();
	
	responseObserver.onNext(response);
	responseObserver.onCompleted();
    }
}
